services:
  debug-board-service:
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Bind mount for X11 display forwarding
    stdin_open: true  # Enable interaction with container (for `-it` in docker run)
    tty: true  # Enable TTY for `-it` functionality
