name: Build doc DevAtServ

on:
  push:
    tags:
      - "rel/das/*.*.*.*"
      - "dev/das/*.*.*.*"

  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.PAT_GITHUB }} 
  TRIGGER_BY: ${{ github.ref_type }}
  TAG_NAME: ${{ github.ref_name }}
  REF_NAME: ${{ github.ref_name }}

jobs:
  devatserv-windows-native:
    name: DevAtServ Windows
    runs-on: windows-latest
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DevAtServ
        shell: bash
        run: |
          cd doc
          python ./genmaindoc.py --configfile "../config/documents/maindoc_config_OSS.json" --bundle_name "DevAtServ" --bundle_version "0.13.1.0" --bundle_version_date "11/2024"

    